version: '3.5'

services:
  id-generation-service-postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: id_generation_service
      POSTGRES_USER: cqdg
      POSTGRES_PASSWORD: password
    ports:
      - 5632:5432
  cqdg-data-submission-adminer:
    image: adminer
    ports:
      - 5280:8080
