name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/id-service
          tag_format: "{sha}-{timestamp}"